us_states_json = [
    "United States - Alabama.json",
    "United States - Alaska.json",
    "United States - Arizona.json",
    "United States - Arkansas.json",
    "United States - California.json",
    "United States - Colorado.json",
    "United States - Connecticut.json",
    "United States - Delaware.json",
    "United States - District of Columbia.json",
    "United States - Florida.json",
    "United States - Georgia.json",
    "United States - Hawaii.json",
    "United States - Idaho.json",
    "United States - Illinois.json",
    "United States - Indiana.json",
    "United States - Iowa.json",
    "United States - Kansas.json",
    "United States - Kentucky.json",
    "United States - Louisiana.json",
    "United States - Maine.json",
    "United States - Montana.json",
    "United States - Nebraska.json",
    "United States - Nevada.json",
    "United States - New Hampshire.json",
    "United States - New Jersey.json",
    "United States - New Mexico.json",
    "United States - New York.json",
    "United States - North Carolina.json",
    "United States - North Dakota.json",
    "United States - Ohio.json",
    "United States - Oklahoma.json",
    "United States - Oregon.json",
    "United States - Maryland.json",
    "United States - Massachusetts.json",
    "United States - Michigan.json",
    "United States - Minnesota.json",
    "United States - Mississippi.json",
    "United States - Missouri.json",
    "United States - Pennsylvania.json",
    "United States - Rhode Island.json",
    "United States - South Carolina.json",
    "United States - South Dakota.json",
    "United States - Tennessee.json",
    "United States - Texas.json",
    "United States - Utah.json",
    "United States - Vermont.json",
    "United States - Virginia.json",
    "United States - Washington.json",
    "United States - West Virginia.json",
    "United States - Wisconsin.json",
    "United States - Wyoming.json"
]